services:
  server:
    build: .
    ports:
      - "8080:8080"
  postgres:
    image: postgres:17.4-alpine
    container_name: go-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: bookdatabase
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
volumes:
  postgres_data: